### 개인 복습

In [40]:
lis = [1,2,3,1,4,2,1]


def allindex(a,b):
    newlist = []
    for i, e in enumerate(a):
        if e == b:
            newlist.append(i)
    return newlist

allindex(lis,1)

[0, 3, 6]

In [41]:
def func(a,b,c):
    print(a,b,c)

x=[1,2,3]
func(*x)   # x를 언패킹 해주는 것. 따라서 x만 쓰면 오류

1 2 3


In [42]:
def func(*args):   # func안에 것들을 패킹
    for arg in args:
        print(arg)
        
func(1,2,3,4,5)  

1
2
3
4
5


In [43]:
def func(email,name):
    print("이메일 : ",email)
    print("이름 : ",name)

x = {"email":"aa@aa.com","name":"tom"}
func(**x)

이메일 :  aa@aa.com
이름 :  tom


In [44]:
def func(**kwargs):
    print("이메일 : ",kwargs["email"])
    print("이름 : ",kwargs["name"])
    
func(email="aa@aa.com",name="tom")

이메일 :  aa@aa.com
이름 :  tom


In [45]:


def calc(operator, *nums):
    sum = 0  # 로컬변수
    for num in nums:
        if operator == "+":
            sum += num
        elif operator == "*":
            if sum==0:
                sum=1
            sum *= num
    return sum

calc("*",1,2,3,4,5)

120

### 수업 복습

In [46]:
def func1():
    def func2():
        print("school")
    func2()  #바깥에서는 활용할 수 없음

func1()  # func의 사용범위 중요함

school


In [47]:
class Dog:   # 간단하게 클래스 정의
    def __init__(self, name, color):
        self.hungry = 0
        self.name = name
        self.color = color
        
    def eat(self):
        self.hungry -= 10
        print("밥먹음",self.hungry)
    def walk(self):
        self.hungry += 10
        print("산책",self.hungry)
    def showme(self):
        print(f"{self.name} : {self.color}")

In [48]:
choco = Dog("choco","black")   # init이 없으므로 # 객체 생성
choco.eat()
choco.eat()
choco.walk()
choco.showme()

밥먹음 -10
밥먹음 -20
산책 -10
choco : black


In [49]:
jjong = Dog("jjong","white")
print(jjong.hungry)
jjong.hungry = 10
print(jjong.hungry)

0
10


In [50]:
choco.eat()

밥먹음 -20


In [51]:
class Account:    # 계좌라고 한다면?
    def __init__(self):
        self.balance=0
    def withdraw(self,amount): 
        self.balance -= amount
    def deposit(self, amount):
        self.balance += amount

In [52]:
class Dog:   
    def __init__(self, name, color):
        self.__hungry = 0  # __ : 비공개속성
        self.name = name
        self.color = color
        
    def eat(self):
        self.__hungry -= 10
        self.bark = "walwal"
        print("밥먹음",self.__hungry, self.bark)
    def walk(self):
        self.__hungry += 10
        print("산책",self.__hungry)
    def showme(self):
        print(f"{self.name} : {self.color}")

In [53]:
mery = Dog("mery","black")
mery.eat()    # 내부에서는 사용 가능
mery.walk()
mery.walk()

밥먹음 -10 walwal
산책 0
산책 10


In [54]:
print(mery.bark)  # 똑같이 __ 넣었는데, 외부에서는 사용 불가
                  # bark는 외부 사용 가능해서 walwal 뜨지만, __hungry는 사용 불가

walwal


In [55]:
print(mery.__hungry)

AttributeError: 'Dog' object has no attribute '__hungry'

In [ ]:
class Dog:
    dog_count = 0
    def __init__(self, name, color):
        self.name = name
        self.color = color
        self.dog_count = 0
        Dog.dog_count += 1  # 객체 생성 시 count 1개씩 늘어남
    def dogCount(self):
        self.dog_count += 1  # 해당 객체에만 count 1개씩 늘어남
        print("총 강아지는 :",Dog.dog_count)
        print("내 강아지는 :",self.dog_count)
    

In [ ]:
hello = Dog("hello","black")
hello.dogCount()


In [ ]:
happy = Dog("happy","black")
happy.dogCount()   

In [ ]:
class Car:
    car_count = 0  # 등록된 차량 갯수
    def __init__(self, name, cc, year):
        self.__name = name   # 차이름(private)
        self.__cc = cc      # 배기량(private)
        self.__year = year   # 생산년도(private)
        Car.car_count += 1
    def size(self):
        if self.__cc>2000:    # 배기량에 따라 소, 중, 대형 출력하는 인스턴스 함수
            print("대형",self.__cc)
        elif 1000<=self.__cc<=2000:
            print("중형",self.__cc)
        else:
            print("소형",self.__cc)
    def name(self):         # 차 이름을 확인하는 함수와 변경하는 함수
        print(self.__name)
    def namechange(self):
        new = input("새로운 이름 : ")
        self.__name = new
        print(self.__name)
    def carcount(self):
        print("총 등록된 차량 수는 : ",Car.car_count)  # 총 등록된 차량개수 출력


In [ ]:
benz = Car("benz",3000,2017)

In [ ]:
bmw = Car("bmw",2000,2014)

In [ ]:
audi = Car("audi",1600,2012)

In [ ]:
benz.size()
bmw.size()
audi.size()

In [ ]:
benz.name()
bmw.name()
audi.name()

In [ ]:
audi.carcount()

In [ ]:
audi.namechange()

In [ ]:
audi.name()

In [ ]:
audi.carcount()

In [ ]:
print(audi,name)

In [ ]:
# 박수진 코딩
class Car:
    car_count = 0
    def __init__(self,name,cc,year):
        self.__name = name
        self.__cc = cc
        self.__year = year
        Car.car_count += 1
    def check(self):
        print(self.__name)
    def change(self):
        new_name = input("차 이름을 변경해주세요 :")
        self.__name = new_name
    def car_class(self):
        if self.__cc < 1000:
            print("소형")
        elif self.__cc <= 2000:
            print("중형")
        elif self.__cc > 2000:
            print("대형")
        else: pass
    def carCount(self):
        print("총 등록된 자동차 수는:", Car.car_count)

In [ ]:
morning = Car("morning",2017,2017)

In [ ]:
morning.change()

In [ ]:
morning.check()

In [ ]:
morning.carCount()

### 강사님 모범답안

In [ ]:
class Car:
    carCount=0
    def __init__(self, name, volume, year):
        self.__name = name
        self.__volume = volume
        self.year = year
        Car.carCount += 1
    def get_name(self):
        print(f"차종은 {self.__name}입니다")
        
    def change_name(self, new_name):
        self.__name = new_name
        
    def show_volume(self):
        if self.__volume < 1000:
            print("소형")
        elif self.__volume <= 2000:
            print("중형")
        else:
            print("대형")
            
    @classmethod               # classmethod 하려면 (cls) 들어가야!
    def get_total_cars(cls):
        print("총 등록된 차량개수는 : ",Car.carCount)

In [ ]:
hyundai = Car("i30",1800,2000)
benz = Car("benz",3000,2015)
kia = Car("morning",900,2020)

In [ ]:
hyundai.get_name()

In [ ]:
hyundai.change_name("팰리세이드")
hyundai.get_name()   # 이름 변경만 한 것은 __name 그대로 적용됨!

In [ ]:
Car.get_total_cars()

In [ ]:
class Animal:    # 부모클래스
    def __init__(self):
        self.hungry = 0
    def eat(self):
        self.hungry -= 10
        print("밥먹음", self.hungry)
    
    def walk(self):
        self.hungry += 10
        print("산책",self.hungry)

In [ ]:
class Dog(Animal):  #자식클래스1
    def __init__(self):
        super().__init__()  #부모의 init호출
        
    def sound(self):
        print("멍멍")

In [56]:
class Cat(Animal):  #자식클래스2
    def __init__(self):
        super().__init__()  #부모의 init호출
        
    def sound(self):
        print("야옹")

NameError: name 'Animal' is not defined

In [ ]:
dog = Dog()
dog.sound()

In [ ]:
dog.walk()  #부모 클래스여도 작동됨, 상속으로 그대로 가져옴

In [ ]:
cat=Cat()
cat.sound()

In [ ]:
cat.eat()     #부모 클래스여도 작동됨, 상속으로 그대로 가져옴

In [ ]:
class Dog(Animal):  #자식클래스1
    def __init__(self):
        super().__init__()  #부모의 init호출
        
    def sound(self):
        print("멍멍")
        
    def eat(self, type):
        if type == "밥":
            print("멍멍")
        else:
            print("왈왈")
            
       

In [ ]:
dog=Dog()
dog.eat("밥")  # 부모함수 호출 + 내가 정의한 것 나옴(왈왈)

In [ ]:
dog.eat()    #부모 클래스에 eat 있으나, 자식 클래스에 달라져서 호출할 수 없음

In [ ]:
animal = Animal()
animal.eat()    # 추상클래스는 듣고 넘길 것

In [ ]:
for i in range(10,-10,-1):
    try:
        print(10/i)
    except ZeroDivisionError as e:
        print("에러가 발생했습니다.", e)
       # 어느시점에서 에러가 나는지 모름 (try, except 활용)

In [ ]:
x=[1,2,3]

try:
    a = x[4]   # 인덱스 에러
except Exception as e:
    print("잘못된 인덱스 : ", e)

In [ ]:
import pickle

try:
    with open("data3.p","rb") as file:
        name = pickle.load(file)
        address = pickle.load(file)
        email = pickle.load(file)
        print(f"이름 : {name}, 주소 : {address}, 이메일 : {email}")
        
except:
    name = input("이름을 입력해주세요 : ")
    address = input("주소를 입력해주세요 : ")
    email = input("이메일을 입력해주세요 : ")
    
    with open("data3.p","wb") as file:
        pickle.dump(name, file)
        pickle.dump(address, file)
        pickle.dump(email, file)

In [73]:
import pickle

try:
    with open("data3.p","rb") as file:
        name = pickle.load(file)
        address = pickle.load(file)
        email = pickle.load(file)
        print(f"이름 : {name}, 주소 : {address}, 이메일 : {email}")
        
except:
    name = input("이름을 입력해주세요 : ")
    address = input("주소를 입력해주세요 : ")
    email = input("이메일을 입력해주세요 : ")
    
    with open("data3.p","wb") as file:
        pickle.dump(name, file)
        pickle.dump(address, file)
        pickle.dump(email, file)

이름 : 핀테크, 주소 : 서울, 이메일 : fintech@net


In [63]:
# 실습02
class Notnumber(Exception):
    def __init__(self):
        super().__init__("잘못된 숫자입니다")

In [64]:
def gugudan(num):
    # 에러를 만들어주고 싶다면?
    if num <1 or num>9:
        #error raise
        raise Notnumber
    for i in range(1, 10):
        print(f"{num} * {i} = {num*i}")

In [72]:
try:
    gugudan(10)
except Exception as e:
    print("1에서 9사이 숫자를 넣어주세요")

1에서 9사이 숫자를 넣어주세요


In [79]:
import calc

print(calc.add(5,6))

11


In [80]:
import calc

print(calc.sub(5,6))

-1


In [87]:
from calc import add, sub   #구체적 함수 명시

print(add(5,6))
print(sub(5,6))


11
-1


In [2]:
import calc
print(calc.add(5,6))

ModuleNotFoundError: No module named 'calc'

In [1]:
import pkcalc.calc as calc

In [2]:
print(calc.add(5,6))

11


In [3]:
print(calc.name)

calc


In [1]:
from pkcalc.calc import add, sub, name

In [2]:
print(name)

calc


In [3]:
print(add(5,6))

11


In [3]:
import pkcalc
print(pkcalc.add(5,6))

11


In [7]:
!python pkcalc/calc.py    # 주피터노트북에서 실행하는 것, 시작점이 모듈

module 입니다
14


In [9]:
import sys
print(sys.path)

['/Users/yunhojun/kdigital', '/Users/yunhojun/opt/anaconda3/lib/python38.zip', '/Users/yunhojun/opt/anaconda3/lib/python3.8', '/Users/yunhojun/opt/anaconda3/lib/python3.8/lib-dynload', '', '/Users/yunhojun/opt/anaconda3/lib/python3.8/site-packages', '/Users/yunhojun/opt/anaconda3/lib/python3.8/site-packages/aeosa', '/Users/yunhojun/opt/anaconda3/lib/python3.8/site-packages/IPython/extensions', '/Users/yunhojun/.ipython']


In [10]:
#  sys.path.append("경로") 로 경로 추가할 수 있음
# 그다음 다시 import하면 경로 다시 찾아와서 def 가져올 수 있음

In [11]:
import numpy as np

In [12]:
import pandas as pd

In [1]:
matrix_1=[[1,2],[3,4]]  # 2차원 리스트
matrix_2=[[5,6],[7,8]]

In [18]:
# matrix 원소의 합
matrix_sum = [[],[]]
for i in range(2):
    for j in range(2):
        matrix_sum[i].append(matrix_1[i][j]+matrix_2[i][j])

print(matrix_sum)

[[6, 8], [10, 12]]


In [20]:
# matrix_1의 원소에 1 더하기
matrix_1 = [[1,2],[3,4]]
for i in range(2):
    for j in range(2):
        matrix_1[i][j] += 1
        
print(matrix_1)

[[2, 3], [4, 5]]


In [2]:
# 매트릭스 더하기 강사님 모범답안
def matrix_sum(mat_1,mat_2):
    for i in range(len(matrix_1)):
        for j in range(len(matrix_1[0])):
            mat_1[i][j] += mat_2[i][j]
    
    return mat_1

matrix_sum(matrix_1,matrix_2)
print(matrix_1)

[[6, 8], [10, 12]]


In [7]:
# 매트릭스 원소에 1더하기 (함수 만들어서 쓸 수 있다)

def mat_add_one(mat):
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            mat_1[i][j] += 1
 
mat_add_one(matrix_1)
matrix_1

NameError: name 'mat_1' is not defined

### NUMPY

In [8]:
# 행렬 합을 numpy 식으로 표현
import numpy as np

matrix_1=[[1,2],[3,4]] 
matrix_2=[[5,6],[7,8]]

In [11]:
mat_sum = np.array(matrix_1) + np.array(matrix_2)  #array에는 ,가 없음
print(mat_sum)

[[ 6  8]
 [10 12]]


In [13]:
mat_one_plus = np.array(matrix_1) + 1  # 각 원소에 덧셈이 됨
print(mat_one_plus)   # print를 빼면 array라는 글자가 등장함

[[2 3]
 [4 5]]


In [22]:
# 리스트와 넘파이 걸리는시간 비교
import time

size = 10000000

x = list(range(size))
y = list(range(size))

In [21]:
print(time.localtime())

time.struct_time(tm_year=2020, tm_mon=12, tm_mday=15, tm_hour=17, tm_min=21, tm_sec=54, tm_wday=1, tm_yday=350, tm_isdst=0)


In [30]:
start_time = time.time()
z = [x[i]+y[i] for i in range(size)]
print(f"리스트 걸릴 시간 : {time.time()-start_time}")

리스트 걸릴 시간 : 13.15575385093689


In [32]:
x = np.arange(size)
y = np.arange(size)

In [33]:
start_time = time.time()   # 나중에 행렬 들어가면 시간 더 오래걸림
z = x+y                    # 넘파이 사용하는 이유 : 걸린시간 단축하기 위해서
print(f"넘파이 걸릴 시간 : {time.time()-start_time}")

넘파이 걸릴 시간 : 0.09296417236328125


In [34]:
# 속도를 빠르게하려고 int의 비트를 세분화함
# 넘파이의 자료형은 세세하게 나눠져있다

In [40]:
x = np.uint(32)  # -32를 넣으면 약속이 틀림. 왜냐면 부호 없는거니깐.
print(x)
print(type(x))

32
<class 'numpy.uint64'>


In [42]:
x = np.array([1,2,3,4])   # ,안나옴
print(x)
print(type(x))    # ndarray는 다차원 배열이라는 형태
print(x.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64


In [43]:
x = np.float32([1,2,3,4])
print(x)
print(type(x))    # float으로 바꿔도 x 형태는 ndarray
print(x.dtype)    # 

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float32


In [45]:
x = np.array([1,2,3,4], dtype = np.float16)  # type 바꿔줄 수 있음
print(x)
print(type(x))    
print(x.dtype)

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float16


In [49]:
x = np.int32(x)
print(x.dtype)
print(x)

int32
[1 2 3 4]


In [51]:
np.issubdtype(x.dtype, np.int32)   # type 체크할 때 x.dtype이 np.int32 이냐?

True

In [52]:
# 1차원 array [1,2]와 같은 것을 벡터라고함
# 그냥 1은 0차원. 스칼라라고 함
# 2차원, 3차원 쭉쭉 표현 가능
# shape : 행렬 구조가 몇 by 몇 인지  ex) 2x3 이면 2차원, 사이즈는 2
  # ex) [1,2]는 1x2, 1차원, 사이즈는 2
# 나중에 딥러닝할 때 어려운 게 사이즈 맞추는 거

In [53]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)   # 2x3 행렬이다

(2, 3)


In [54]:
print(x.ndim)   # 2차원이다 [[],[]] 형태이므로

2


In [60]:
x = np.array([[1,2,3],[4,5,6]])
print(x.size)    # size는 6? size는 원소의 개수

6


In [58]:
x = np.array(1)
print(x.size)

1


In [59]:
x = np.array([1,2])
print(x.size)

2


In [61]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [62]:
x=np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [63]:
x = np.arange(1,10,0.5)
print(x)   #float 포함한다

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [64]:
#linspace 균일한 간격으로 리스트 크기만큼의 리스트생성
x = np.linspace(1,20,5)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]


In [65]:
x = np.linspace(1,20,10,endpoint=False)  # 시작값, 끝값, 벡터크기
print(x)

[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


In [66]:
print(x.size)

10


In [67]:
print(x.shape)  # shape는 제일 바깥 괄호부터 원소의 개수를 추출

(10,)


In [68]:
# 행렬 곱셈시 2*3 3*n 등 안에 자릿수 맞추는 것에 유의

In [69]:
# reshape는 shape를 바꿔주는 것
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [73]:
x = x.reshape(3, 3)   # 9와 차원수가 맞아야
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [74]:
x = np.arange(24).reshape(2,3,4)  # 2*3*4 = 24 맞출것
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [75]:
print(x.shape)

(2, 3, 4)


In [76]:
x = np.array([[1,2],[3,4],[5,6]])   # (3,2) 형태
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [77]:
print(x.reshape(2,3))    # (2,3) 형태

[[1 2 3]
 [4 5 6]]


In [78]:
x = np.arange(9).reshape(3,-1)   # -1로 두면 알아서 맞춰줌
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [80]:
x = np.arange(24).reshape(2,3,4)
print(x.reshape(4,3,-1))    # -1은 1개만 쓸 것

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
