### 객체와 클래스 실습02

In [35]:
class Character:
    def __init__(self):  # 외부 파라미터 받는 게 없으므로 only self
        self.health = 200  # health라는 속성 추가, 생성시 200
         # 상속받을 때 프라이빗하면 접근 불가
        
    def move(self):
        self.health -= 10
        
    def rest(self):
        self.health += 10
        
    def checkHealth(self):
        print("Health : ",self.health)

In [34]:
class Knight(Character):
    
    def __init__(self):
        super().__init__()
    
    def move(self):    #move 재정의
        self.health -= 15  #추가적으로 5가 더 소모되므로
        
    def attack(self,character):
        character.move()
        print("공격합니다")
        

In [20]:
knight_1 = Knight()
knight_1.checkHealth()    
# 자식 클래스에서 def init 하면 super init해야 부모 클래스 가져오고 + 자식 자기속성 추가되는 것
# 만약 def init 안하면 그대로 부모 클래스에 있는 것만 가져옴
# 그래서 def init 안했을 때 부모에 있는 Health 200만 가져온 것

Health :  200


In [21]:
knight_1.move()
knight_1.checkHealth()    #10이 아니라 15가 줄어듦

Health :  185


In [22]:
class Healer(Character):
    
    def __init__(self):
        super().__init__()   #이거 해줘야 checkHealth 가져옴
        self.mana = 100    # 속성추가
        
    def heal(self,character):
        self.mana -= 10
        character.rest()  # knight에 체력10 올려주는 걸 표현
        
    def checkMana(self):
        print("현재 mana : ",self.mana)

In [23]:
healer_1 = Healer()
healer_1.checkHealth()   
healer_1.checkMana()

Health :  200
현재 mana :  100


In [25]:
knight_2 = Knight()
knight_2.move()
knight_2.move()
knight_2.checkHealth()     # knight는 추가적으로 5가 더 반영

Health :  170


In [26]:
person = Character()
person.move()
person.move()
person.checkHealth()    

Health :  180


In [27]:
knight_1.checkHealth()
healer_1.heal(knight_1)    #  ()는 인스턴스 집어넣는 곳
healer_1.checkMana()
knight_1.checkHealth()    # 힐러가 마나10 사용해 knight 체력 10 올려줌

Health :  185
현재 mana :  90
Health :  195


In [32]:
person.checkHealth()

Health :  180


In [36]:
knight_1.attack(person)   # 이거는 따로 구성해서 하면 됨
person.checkHealth()

TypeError: attack() takes 1 positional argument but 2 were given

In [37]:
import numpy as np

In [41]:
x = np.linspace(1,20,3)   
x

array([ 1. , 10.5, 20. ])

In [43]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
x.reshape(2,3,-1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [46]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
print(x[1:3])   #1차원 슬라이싱

[1 2]


In [51]:
x=np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [54]:
print(x[1:3])

[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [55]:
print(x[1:3,1:3])  # 2차원 슬라이싱

[[ 6  7]
 [11 12]]


In [57]:
print(x[1:3,1])  # 차원 수 하나 줄어듦

[ 6 11]


In [58]:
print(x[1:3,1:2])  

[[ 6]
 [11]]


In [59]:
x = np.arange(30).reshape(2,5,3)   #3차원
x

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

In [66]:
print(x[:,3:5,1])   # 3차원 슬라이싱

[[10 13]
 [25 28]]


In [76]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
print(a[1][1])

6


In [69]:
print(a[1,1])

6


In [72]:
print(a[[1,1],[1,2]])

[6 7]


In [71]:
print(a[a>3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [73]:
print(a[a==1])

[1]


In [77]:
print(a[-(a==1)])

TypeError: The numpy boolean negative, the `-` operator, is not supported, use the `~` operator or the logical_not function instead.

In [79]:
print(a[a != 1])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [80]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [81]:
a[1][1]

6

In [82]:
a[1,1]

6

In [83]:
a[[1,1],[1,2]]

array([6, 7])

In [84]:
a = np.arange(20).reshape(2,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [85]:
a[1][1]

11

In [86]:
a[1,1]

11

In [87]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
a[[1,1],[1,2]]

array([6, 7])

In [89]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [90]:
a[a==1]

array([1])

In [104]:
a[(a!=1)]

array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [106]:
a[(a<3) |(a>8)]

array([ 0,  1,  2,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [103]:
print(a<8)

[[ True  True  True  True  True]
 [ True  True  True False False]
 [False False False False False]
 [False False False False False]]


In [108]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
print(a[1][1])

6


In [111]:
print(a[1,1])

6


In [113]:
print(a[[1,1],[1,2]])

[6 7]


In [114]:
print(a>3)

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [115]:
print(a[a>3])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [116]:
print(a[a==1])

[1]


In [117]:
print(a[~(a==1)])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [118]:
print(a[(a>3)&(a<8)])

[4 5 6 7]


In [125]:
np.random.rand(5,5)   # 5x5 행렬의 랜덤 수를 입력

array([[0.10202309, 0.61729563, 0.86366319, 0.57788432, 0.38593459],
       [0.29936318, 0.29490935, 0.21713423, 0.16037735, 0.31514827],
       [0.29088492, 0.20388207, 0.22474127, 0.82876035, 0.84534471],
       [0.3682914 , 0.9887219 , 0.83747528, 0.53607754, 0.95657223],
       [0.28245896, 0.26047386, 0.58184462, 0.64429555, 0.03990616]])

In [127]:
np.random.randint(1,10)

6

In [129]:
np.random.randint(1,10,size=(5))

array([3, 1, 1, 2, 3])

In [132]:
np.random.randint(1,10,size=(5,5))

array([[4, 3, 5, 5, 1],
       [6, 1, 4, 1, 1],
       [2, 8, 4, 2, 5],
       [2, 4, 7, 9, 8],
       [7, 6, 6, 5, 8]])

In [134]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [136]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [139]:
a.ravel()    # a행렬 행벡터로 펼치기

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [141]:
a.ravel(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [142]:
a.ravel(order='F')

array([ 0,  5, 10, 15,  1,  6, 11, 16,  2,  7, 12, 17,  3,  8, 13, 18,  4,
        9, 14, 19])

In [143]:
x = np.arange(1,4)
x

array([1, 2, 3])

In [144]:
y = np.arange(4,7)
y

array([4, 5, 6])

In [145]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [150]:
x = np.arange(10).reshape(2,5)
y = np.arange(10,20).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [151]:
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [153]:
np.concatenate([x,y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [154]:
np.concatenate([x,y],axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [155]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [162]:
np.split(x,4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [164]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [165]:
np.split(x,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [166]:
np.split(x,2,axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [167]:
np.random.choice

<function RandomState.choice>

In [169]:
x = np.array([1,2,3])
x+1

array([2, 3, 4])

In [170]:
x = np.arange(1,10).reshape(3,3)
y = np.arange(1,4)
x+y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [172]:
x = np.array([10,20,30]).reshape(3,1)
y = np.arange(1,4)
x+y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [175]:
x = np.arange(4).reshape(2,2)
y = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [174]:
x.dot(y)

array([[ 2,  3],
       [ 6, 11]])

In [176]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [177]:
np.linalg.inv(x)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [178]:
np.median(x)

1.5

In [179]:
np.std(x)

1.118033988749895

In [180]:
np.mean(x)

1.5

In [181]:
np.var(x)

1.25

In [182]:
np.sum(x)

6

In [183]:
np.sum(x,axis=1)

array([1, 5])

In [184]:
np.cumsum(x)

array([0, 1, 3, 6])

In [185]:
np.cumprod(x)

array([0, 0, 0, 0])

In [186]:
np.min(x)

0

In [187]:
np.argmin(x)

0

In [188]:
np.argmax(x)

3

In [189]:
x.dot(inv_x)

NameError: name 'inv_x' is not defined

In [190]:
np.any(x>4)

False

In [191]:
np.all(x>4)

False

In [198]:
np.where(x>1)  

(array([1, 1]), array([0, 1]))

In [196]:
np.where(x>1,x,-100)  # 다 false여서 -100으로 추출

array([[-100, -100],
       [   2,    3]])

In [199]:
1.25 ** 0.5

1.118033988749895

In [200]:
np.sum(x)

6

In [201]:
np.sum(x,axis=0)

array([2, 4])

In [202]:
np.argmax(x)

3

In [203]:
np.argmin(x)

0

In [204]:
np.any(x>2)

True

In [205]:
np.all(x>1)

False

In [206]:
np.where(x>2)

(array([1]), array([1]))

In [207]:
a = np.array([10,3,-5,2,7,4])
a

array([10,  3, -5,  2,  7,  4])

In [208]:
np.where(a>4)

(array([0, 4]),)

In [210]:
np.where(a>4,a,-100)

array([  10, -100, -100, -100,    7, -100])

In [4]:
import numpy as np

In [17]:
#실습01

x = [1,2,3,4,5,6,7,8,9]
y = [10,20,30,40,50,60,70,80,90]

x = np.array([1,2,3,4,5,6,7,8,9])    # 리스트를 넘파이 형태로
y = np.array([10,20,30,40,50,60,70,80,90])

x = x.reshape(3,3)
y = y.reshape(3,3)

In [18]:
# 실습01 행렬합
x+y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [19]:
#실습01 행렬곱
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [21]:
#실습02
a = np.linspace(1,20,30)   #균일한 간격 리스트 생성
a+10

array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [68]:
#실습03
b = np.random.randint(1,100,size=(2,10,10))  #무작위 행렬 생성
b = np.where(b>=50,1,2)   #조건을 통한 숫자 반환
print(b[1:2, 5:10, 5:10])   #가장 바깥 괄호부터 적용

[[[2 1 2 1 1]
  [1 2 2 2 2]
  [1 2 2 1 2]
  [1 1 2 2 1]
  [2 1 1 2 1]]]


In [69]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Pandas

In [71]:
import pandas as pd

In [72]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
np.where(a>4)     # 각 자리 숫자 조합해서 인덱스 (1,2),(2,0),(2,1),(2,2)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [74]:
x = [1,2,3,4,5]   # 앞이 인덱스, 뒤에 숫자
s = pd.Series(x)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [76]:
print(s.index)   # range를 표현

RangeIndex(start=0, stop=5, step=1)


In [77]:
s.values   # numpy의 array

array([1, 2, 3, 4, 5])

In [78]:
type(s.values)

numpy.ndarray

In [79]:
s = pd.Series(x, index=['a','b','c','d','e'])
s  # index가 a~e로 표현됨  object로 바뀜

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [80]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [81]:
s['c']

3

In [82]:
s[2]   #여전히 숫자로 표기된 인덱스도 가지고 있음

3

In [86]:
s[['b','d']]

b    2
d    4
dtype: int64

In [88]:
s[[0,3]]

a    1
d    4
dtype: int64

In [90]:
s.a    # 값만 표시됨

1

In [91]:
x = [1,2,3,4,5]

In [92]:
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [93]:
x = np.array([1,2,3,4,5])
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [94]:
# 딕셔너리는 키 중복이 안됨, 키가 인덱스가 됨, 숫자 인덱스도 가지고 있음
x = {'수학':90,'영어':80,'과학':95,'미술':80}
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [95]:
x.index

Index(['수학', '영어', '과학', '미술'], dtype='object')

In [96]:
x['수학']

90

In [97]:
x['미술']

80

In [98]:
# 슬라이싱 가능
x['영어':]

영어    80
과학    95
미술    80
dtype: int64

In [100]:
x['영어':'과학']  # 끝을 포함한다!

영어    80
과학    95
dtype: int64

In [101]:
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [103]:
part = pd.Series(x, index=['수학','영어','과학']) #해당 인덱스만 가져옴

In [104]:
part

수학    90
영어    80
과학    95
dtype: int64

In [150]:
# 인덱스를 여러개 만들 수도 있음 Grouping
student_1 = {'수학':90,'영어':80,'과학':95,'미술':80}
student_2 = {'수학':70,'영어':90,'과학':100,'미술':70}

In [151]:
index_1 = ['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]
index_1






['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']

In [145]:
index_2 = list(student_1.keys())
index_2

['수학', '영어', '과학', '미술']

In [146]:
value_all = list(student_1.values()) + list(student_2.values())
value_all

[90, 80, 95, 80, 70, 90, 100, 70]

In [152]:
students = pd.Series(value_all, index=[index_2,index_1])
students

ValueError: all arrays must be same length

In [153]:
print("hello world")

hello world


In [177]:
# 결측값 처리방법
x = [1,None,2,None,3,4,None]  #python code
x

[1, None, 2, None, 3, 4, None]

In [156]:
x = pd.Series(x)   # None 입력했던 것이 NaN으로 나옴
x

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [157]:
print(x.sum())   #값 있는 것들만 계산. 에러를 내지 않음

10.0


In [158]:
print(x.max())

4.0


In [159]:
print(x.min())    # None은 값에 포함하지 않음. 그래서 1이 제일 min값

1.0


In [162]:
print(x.isnull().sum())   #isnull은 NaN과 똑같음. 결측값이면 True 반환
# sum까지 붙이면 결측값의 개수를 반환

3


In [163]:
x.dropna()    #결측치 제거. index숫자는 그대로 남아있음

0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [164]:
x

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [165]:
x.fillna(0)   #Nan을 0으로 채우겠다

0    1.0
1    0.0
2    2.0
3    0.0
4    3.0
5    4.0
6    0.0
dtype: float64

In [166]:
x   # but 여전히 x 원본값은 바뀌지 않음

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
5    4.0
6    NaN
dtype: float64

In [172]:
#concat
x = pd.Series([1,2,3])
y = pd.Series([4,5,6])
z = pd.Series([7,8,9])

In [183]:
# 합치면서 인덱스 번호 다시 정리 : ignore_Index(True)
# 축변경 axis=1

x = pd.Series([1,2,3,4])
y = pd.Series([4,5,6])
z = pd.Series([7,8,9])

In [184]:
# 개수 맞지 않을 때 교집합, 합집합 : 맞지 않는 부분 결측치로 채운다

In [185]:
print(x.add(10))

0    11
1    12
2    13
3    14
dtype: int64


In [186]:
print(x.add(y))  # 맞지 않는 부분 NaN 처리

0    5.0
1    7.0
2    9.0
3    NaN
dtype: float64


In [187]:
print(x.mod(2))  #2로 나눈 나머지 반환
#파이썬과 다르게 for 루프 안돌려도 편하게 활용할 수 있다

0    1
1    0
2    1
3    0
dtype: int64


In [188]:
x.count()  #파이썬 len하고 같음

4

In [189]:
x.describe()  #다 알려줌
# 50% median , 75%는 상위 75% 숫자 , 25는 상위 25% 숫자

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64

In [190]:
x.head(2)  #앞에서 2개만

0    1
1    2
dtype: int64

In [191]:
x.tail(2)   #뒤에서 2개만

2    3
3    4
dtype: int64